# Name of workflow
name: Python CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

      # strategy:
      # Node versions list
      # matrix:
      # node-version: [20.x]

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
        # Клонируем репозиторий
      - uses: actions/checkout@v4
        # Step's name
      - name: Set up Python3
        # Configures the Python version used on GitHub-hosted runners
        # https://github.com/actions/setup-python
        # Устанавливаем Python
        uses: actions/setup-python@v4
        # The Node.js version to configure
        # with:
        # node-version: ${{ matrix.node-version }}
        #  cache: 'npm'
        # make depends on poetry
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          make install
      - name: Run linter
        run: |
          make check
      - name: Test & publish code coverage
      #   # Publish code coverage on Code Climate
      #   # https://github.com/paambaati/codeclimate-action
      #   # Add Code Climate secret key
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: 4deda40d2851fe9a305474a12971b43a1ec1d68f6772c8d43befa4fd2a837067
        with:
          coverageCommand: make test-coverage
          debug: true
